#!/bin/bash
# SSH Menu - by znand-dev

# Warna
NC='\e[0m'
GREEN='\e[1;32m'
YELLOW='\e[1;33m'
CYAN='\e[1;36m'

clear
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}              🔐 MENU SSH & OVPN 🔐                ${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}[1]${NC} Tambah User SSH"
echo -e "${GREEN}[2]${NC} Hapus User SSH"
echo -e "${GREEN}[3]${NC} Cek Login Aktif"
echo -e "${GREEN}[4]${NC} Cek Semua Akun Aktif"
echo -e "${GREEN}[5]${NC} Restart Service SSH / Dropbear / Stunnel"
echo -e "${GREEN}[x]${NC} Kembali ke menu utama"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -p "👉 Pilih opsi: " opt

case $opt in
1) bash /etc/autoscriptvpn/ssh/add-ssh.sh ;;
2) bash /etc/autoscriptvpn/ssh/del-ssh.sh ;;
3) bash /etc/autoscriptvpn/ssh/cek-login.sh ;;
4) bash /etc/autoscriptvpn/ssh/cek-aktif.sh ;;
5) bash /etc/autoscriptvpn/ssh/restart-ssh.sh ;;
x) menu ;;
*) echo "Pilihan salah bro!" ; sleep 1 ; m-sshovpn ;;
esac
