#!/bin/bash
# Menu Tools by znand-dev

# Warna
CYAN='\e[1;36m'
GREEN='\e[1;32m'
YELLOW='\e[1;33m'
NC='\e[0m'

clear
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}                 ⚙️ MENU TOOLS                  ${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}[1]${NC} Backup & Restore Config"
echo -e "${GREEN}[2]${NC} Speedtest VPS"
echo -e "${GREEN}[3]${NC} Ganti Domain XRAY"
echo -e "${GREEN}[x]${NC} Kembali ke menu utama"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -p "👉 Pilih opsi: " opt

case $opt in
1) bash /etc/autoscriptvpn/tools/backup.sh ;;
2) bash /etc/autoscriptvpn/tools/speedtest.sh ;;
3) bash /etc/autoscriptvpn/tools/domain.sh ;;
x) menu ;;
*) echo "❌ Pilihan salah!" ; sleep 1 ; tools-menu ;;
esac
